---
# defaults file for jenkins_teardown
aws_region: us-east-1
vpc_cidr: 10.0.0.0/16
vpc_name: "jenkins-{{ aws_region}}-vpc"
vpc_subnets:
  private-1:
    cidr: 10.0.1.0/24
    az: "{{ aws_region }}b"
  private-2:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}c"
  private-3:
    cidr: 10.0.3.0/24
    az: "{{ aws_region }}a"
vpc_security_groups:
  - name: ssh
    description: "Open SSH port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
