- name: Install aptitude using apt
  become: yes
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages
  become: yes
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  become: yes
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Module for Python
  become: yes
  pip:
    name: docker

# - name: Pull default Docker image
#   docker_image:
#     name: "{{ default_container_image }}"
#     source: pull

# # Creates the number of containers defined by the variable create_containers, using values from vars file
# - name: Create default containers
#   docker_container:
#     name: "{{ default_container_name }}{{ item }}"
#     image: "{{ default_container_image }}"
#     command: "{{ default_container_command }}"
#     state: present
#   with_sequence: count={{ create_containers }}

- name: add jenkins to sudo and docker user group
  raw: sudo usermod -aG sudo,docker jenkins

- name: restart jenkins
  raw: sudo /etc/init.d/jenkins restart

- name: add jenkins to sudo user group again
  raw: sudo usermod -aG sudo jenkins

- name: restart jenkins again
  raw: sudo /etc/init.d/jenkins restart
