apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.spec.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
