---
## Create cluster with kops

- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - install-kubectl
    - install-kops
    - install-boto
    - generate-ssh-key-pair
    - create-cluster
    - metrics-server
    - ingress-controller-tls
    - cluster-autoscaler
    - networking

# - hosts: ec2bastion
#   user: ubuntu
#   vars:
#     ansible_ssh_private_key_file: "{{ ssh_private_key }}"
#   gather_facts: true
#   roles:
#     - create-db-from-bastion
