---
# tasks file for jenkins_teardown
- name: Check for running EC2 instances to Terminate
  ec2_instance_info:
    region: "{{ aws_region }}"
    profile: "{{ aws_root }}"
    filters:
      "tag:Name": "{{ tag_value }}"
      instance-state-name: [ "running" ]
  register: existing_ec2

- name: Terminate EC2 Instance
  ec2:
    state: absent
    region: "{{ aws_region }}"
    profile: "{{ aws_root }}"
    instance_id: "{{ existing_ec2.instances[0].instance_id }}"
    wait: yes
  when: existing_ec2.instances

- ec2_vpc_net_info:
    region: "{{ aws_region }}"
    profile: "{{ aws_root }}"
    filters:
      "tag:Name": "jenkins-{{ aws_region}}-vpc"
  register: vpc

- name: Destroy vpc security groups
  ec2_group:
    state: absent
    profile: "{{ aws_root }}"
    region: "{{ aws_region }}"
    name: "jenkins_sg_{{ vpc.vpcs[0].id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    tags:
      Name: "jenkins_sg"

- name: Destroy subnets
  ec2_vpc_subnet:
    state: absent
    region: "{{ aws_region }}"
    profile: "{{ aws_root }}"
    az: "{{ item.value.az }}"
    vpc_id: "{{ vpc.vpcs[0].id }}"
    cidr: "{{ item.value.cidr }}"
    tags:
      Name: "jenkins_{{ item.value.az }}"
  with_dict: "{{ vpc_subnets }}"

- name: Destroy Internet Gateway
  ec2_vpc_igw:
    state: absent
    region: "{{ aws_region }}"
    profile: "{{ aws_root }}"
    vpc_id: "{{ vpc.vpcs[0].id }}"
    tags:
      Name: "jenkins-igw"
  register: jenkins_igw

- name: Grab the route tables
  ec2_vpc_route_table_facts:
    profile: "{{ aws_root }}"
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ vpc.vpcs[0].id }}"
  register: jenkins_route_table

#- name: Destroy RT
#  ec2_vpc_route_table:
#    state: absent
#    lookup: id
#    route_table_id: "{{ jenkins_route_table.route_tables[0].id }}"
#    vpc_id: "{{ vpc.vpcs[0].id }}"
#    profile: "{{ aws_root }}"
#    region: "{{ aws_region }}"
#    tags:
#      Name: "jenkins_route_table_{{ vpc.vpcs[0].id }}"

- name: Remove subdomain with Elastic IP
  route53:
    state: absent
    zone: "{{  domain_name }}"
    record: "{{ sub_domain_name }}"
    type: A
    ttl: 60
    value: "{{ eip }}"
    wait: yes
    profile: "{{ aws_root }}"
    overwrite: yes

- name: Destroy the VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    profile: "{{ aws_root }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ aws_region }}"
    state: absent
    tags:
      Name: "{{ vpc_name }}"
    tenancy: default

