---
## Install Kubectl tasks

- name: Check if kubectl already installed
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl

- name: Download and Install Kubectl
  get_url:
    url: "{{ kubectl_download_path }}/{{ item }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    force: yes
  with_items:
    - kubectl
  become: true
  when: kubectl.stat.exists == false
