apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9308"
    spec:
      containers:
        - name: kafka-exporter
          image: "danielqsj/kafka-exporter:latest"
          imagePullPolicy: Always
          ports:
            - name: "kexporter"
              containerPort: 9308
              protocol: TCP
          args:
            - --kafka.server=kafka:9092
            - --zookeeper.server=kafka-zookeeper:2181
          # readinessProbe:
          #   httpGet:
          #     port: 9308
          #     path: /
          #   initialDelaySeconds: 15
          #   periodSeconds: 30
